#! /bin/bash

sw_topdir[0]=$HOME/files/site
sw_topdir[1]=$HOME/files/poem/site
sw_topdir[2]=$HOME/exam

sw_mddir[0]=md
sw_mddir[1]=md
sw_mddir[2]=md

sw_alias[0]=site
sw_alias[1]=poem
sw_alias[2]=exam

sw_gitdir[0]=$HOME/bkp/codeberg/pages
sw_gitdir[1]=$HOME/bkp/codeberg/poem

sw_commit[0]="..."
sw_commit[1]="..."

sw_branch[0]="master"
sw_branch[1]="pages"

sw_remote[0]="pages"
sw_remote[1]="poem"


